In [8]:
import tensorflow as tf
from tensorflow import keras

from time import time
from tensorflow.python.keras.callbacks import TensorBoard

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print(tf.__version__)

2.0.0-beta0


In [2]:
PATH = os.getcwd()

X_train = pd.read_csv(PATH + "/Train/X_train_3FS.csv", header=0)
Y_train = pd.read_csv(PATH + "/Train/Y_train_3FS.csv", header=0)

X_test = pd.read_csv(PATH + "/Test/X_test_3FS.csv", header=0)
Y_test = pd.read_csv(PATH + "/Test/Y_test_3FS.csv", header=0)

In [3]:
tensorboard = TensorBoard(log_dir = "logs/{}".format(time()))

In [4]:
inputs = keras.Input(shape=(17,))
h1 = keras.layers.Dense(256, activation='relu')(inputs)
h1 = keras.layers.Dropout(0.5)(h1)
#block1_out = layers.MaxPooling2D(3)(h1)

h2 = keras.layers.Dense(256, activation='relu')(h1)
h2 = keras.layers.Dropout(0.5)(h2)
block2_out = keras.layers.add([h2, h1])

h3 = keras.layers.Dense(256, activation='relu')(block2_out)
h3 = keras.layers.Dropout(0.5)(h3)

h4 = keras.layers.Dense(256, activation='relu')(h3)
h4 = keras.layers.Dropout(0.5)(h4)

block4_out = keras.layers.add([h4, h3])

outputs = keras.layers.Dense(3, activation='softmax')(block4_out)

model = keras.Model(inputs, outputs, name='small resnet')
model.summary()

adm = keras.optimizers.Adam(lr=0.00005, beta_1=0.9, beta_2=0.999, epsilon=None,  amsgrad=False)
#Nadam = keras.optimizers.Nadam(lr=0.002, beta_1=0.9, beta_2=0.999, epsilon=None, schedule_decay=0.004)

model.compile(optimizer= adm,
              loss='categorical_crossentropy',
              metrics=['accuracy']) 

#model.fit(X_train, Y_train, batch_size=64, epochs=1000, shuffle=True, verbose=1, validation_split=0.1)
model.fit(X_train, Y_train, batch_size=64, epochs=400, shuffle=True, verbose=1, validation_split=0.1,callbacks=[tensorboard])
print('\ntest set:')
loss = model.evaluate(X_test, Y_test, batch_size=64, verbose=1)

W0919 23:01:23.719666 4446709184 deprecation.py:323] From /Users/JunxiChen/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Model: "small resnet"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 17)]         0                                            
__________________________________________________________________________________________________
dense (Dense)                   (None, 256)          4608        input_1[0][0]                    
__________________________________________________________________________________________________
dropout (Dropout)               (None, 256)          0           dense[0][0]                      
__________________________________________________________________________________________________
dense_1 (Dense)                 (None, 256)          65792       dropout[0][0]                    
_______________________________________________________________________________________

Epoch 35/400
32000/32000 [==============================] - 1s 33us/sample - loss: 0.6744 - accuracy: 0.6795 - val_loss: 0.6796 - val_accuracy: 0.6901
Epoch 36/400
32000/32000 [==============================] - 1s 33us/sample - loss: 0.6761 - accuracy: 0.6797 - val_loss: 0.6784 - val_accuracy: 0.6918
Epoch 37/400
32000/32000 [==============================] - 1s 33us/sample - loss: 0.6738 - accuracy: 0.6806 - val_loss: 0.6788 - val_accuracy: 0.6912
Epoch 38/400
32000/32000 [==============================] - 1s 33us/sample - loss: 0.6716 - accuracy: 0.6832 - val_loss: 0.6790 - val_accuracy: 0.6918
Epoch 39/400
32000/32000 [==============================] - 1s 33us/sample - loss: 0.6728 - accuracy: 0.6814 - val_loss: 0.6766 - val_accuracy: 0.6929
Epoch 40/400
32000/32000 [==============================] - 1s 33us/sample - loss: 0.6718 - accuracy: 0.6825 - val_loss: 0.6758 - val_accuracy: 0.6938
Epoch 41/400
32000/32000 [==============================] - 1s 34us/sample - loss: 0.6702 - ac

32000/32000 [==============================] - 1s 33us/sample - loss: 0.6142 - accuracy: 0.7156 - val_loss: 0.6219 - val_accuracy: 0.7132
Epoch 144/400
32000/32000 [==============================] - 1s 33us/sample - loss: 0.6137 - accuracy: 0.7165 - val_loss: 0.6226 - val_accuracy: 0.7137
Epoch 145/400
32000/32000 [==============================] - 1s 33us/sample - loss: 0.6126 - accuracy: 0.7179 - val_loss: 0.6201 - val_accuracy: 0.7143
Epoch 146/400
32000/32000 [==============================] - 1s 33us/sample - loss: 0.6135 - accuracy: 0.7147 - val_loss: 0.6202 - val_accuracy: 0.7148
Epoch 147/400
32000/32000 [==============================] - 1s 34us/sample - loss: 0.6097 - accuracy: 0.7176 - val_loss: 0.6188 - val_accuracy: 0.7137
Epoch 148/400
32000/32000 [==============================] - 1s 34us/sample - loss: 0.6148 - accuracy: 0.7163 - val_loss: 0.6201 - val_accuracy: 0.7154
Epoch 149/400
32000/32000 [==============================] - 1s 33us/sample - loss: 0.6138 - accuracy:

Epoch 197/400
32000/32000 [==============================] - 1s 33us/sample - loss: 0.5976 - accuracy: 0.7232 - val_loss: 0.6059 - val_accuracy: 0.7182
Epoch 198/400
32000/32000 [==============================] - 1s 33us/sample - loss: 0.5982 - accuracy: 0.7218 - val_loss: 0.6059 - val_accuracy: 0.7188
Epoch 199/400
32000/32000 [==============================] - 1s 33us/sample - loss: 0.5979 - accuracy: 0.7252 - val_loss: 0.6044 - val_accuracy: 0.7202
Epoch 200/400
32000/32000 [==============================] - 1s 33us/sample - loss: 0.5975 - accuracy: 0.7240 - val_loss: 0.6045 - val_accuracy: 0.7193
Epoch 201/400
32000/32000 [==============================] - 1s 33us/sample - loss: 0.5948 - accuracy: 0.7258 - val_loss: 0.6048 - val_accuracy: 0.7222
Epoch 202/400
32000/32000 [==============================] - 1s 33us/sample - loss: 0.5965 - accuracy: 0.7222 - val_loss: 0.6050 - val_accuracy: 0.7205
Epoch 203/400
32000/32000 [==============================] - 1s 33us/sample - loss: 0.59

Epoch 251/400
32000/32000 [==============================] - 1s 36us/sample - loss: 0.5861 - accuracy: 0.7303 - val_loss: 0.5955 - val_accuracy: 0.7222
Epoch 252/400
32000/32000 [==============================] - 1s 35us/sample - loss: 0.5859 - accuracy: 0.7303 - val_loss: 0.5961 - val_accuracy: 0.7213
Epoch 253/400
32000/32000 [==============================] - 1s 35us/sample - loss: 0.5869 - accuracy: 0.7303 - val_loss: 0.5970 - val_accuracy: 0.7233
Epoch 254/400
32000/32000 [==============================] - 1s 36us/sample - loss: 0.5861 - accuracy: 0.7281 - val_loss: 0.5960 - val_accuracy: 0.7216
Epoch 255/400
32000/32000 [==============================] - 1s 36us/sample - loss: 0.5870 - accuracy: 0.7281 - val_loss: 0.5953 - val_accuracy: 0.7233
Epoch 256/400
32000/32000 [==============================] - 1s 36us/sample - loss: 0.5840 - accuracy: 0.7313 - val_loss: 0.5956 - val_accuracy: 0.7233
Epoch 257/400
32000/32000 [==============================] - 1s 35us/sample - loss: 0.58

Epoch 305/400
32000/32000 [==============================] - 1s 35us/sample - loss: 0.5775 - accuracy: 0.7318 - val_loss: 0.5891 - val_accuracy: 0.7244
Epoch 306/400
32000/32000 [==============================] - 1s 35us/sample - loss: 0.5785 - accuracy: 0.7326 - val_loss: 0.5896 - val_accuracy: 0.7236
Epoch 307/400
32000/32000 [==============================] - 1s 34us/sample - loss: 0.5759 - accuracy: 0.7351 - val_loss: 0.5881 - val_accuracy: 0.7264
Epoch 308/400
32000/32000 [==============================] - 1s 34us/sample - loss: 0.5745 - accuracy: 0.7364 - val_loss: 0.5870 - val_accuracy: 0.7247
Epoch 309/400
32000/32000 [==============================] - 1s 35us/sample - loss: 0.5732 - accuracy: 0.7342 - val_loss: 0.5880 - val_accuracy: 0.7255
Epoch 310/400
32000/32000 [==============================] - 1s 34us/sample - loss: 0.5733 - accuracy: 0.7356 - val_loss: 0.5874 - val_accuracy: 0.7258
Epoch 311/400
32000/32000 [==============================] - 1s 35us/sample - loss: 0.57

Epoch 359/400
32000/32000 [==============================] - 1s 35us/sample - loss: 0.5659 - accuracy: 0.7410 - val_loss: 0.5824 - val_accuracy: 0.7328
Epoch 360/400
32000/32000 [==============================] - 1s 35us/sample - loss: 0.5672 - accuracy: 0.7406 - val_loss: 0.5822 - val_accuracy: 0.7340
Epoch 361/400
32000/32000 [==============================] - 1s 35us/sample - loss: 0.5685 - accuracy: 0.7362 - val_loss: 0.5832 - val_accuracy: 0.7300
Epoch 362/400
32000/32000 [==============================] - 1s 36us/sample - loss: 0.5672 - accuracy: 0.7397 - val_loss: 0.5813 - val_accuracy: 0.7317
Epoch 363/400
32000/32000 [==============================] - 1s 36us/sample - loss: 0.5678 - accuracy: 0.7392 - val_loss: 0.5819 - val_accuracy: 0.7323
Epoch 364/400
32000/32000 [==============================] - 1s 34us/sample - loss: 0.5692 - accuracy: 0.7384 - val_loss: 0.5818 - val_accuracy: 0.7326
Epoch 365/400
32000/32000 [==============================] - 1s 35us/sample - loss: 0.56

In [5]:
model.save(os.getcwd() + '/NN_models/5layers_residual2.h5')

In [6]:
model = keras.models.load_model(os.getcwd() + '/NN_models/5layers_residual2.h5')

In [7]:
adm1 = keras.optimizers.Adam(lr=0.00001, beta_1=0.9, beta_2=0.999, epsilon=None,  amsgrad=False)
#Nadam = keras.optimizers.Nadam(lr=0.002, beta_1=0.9, beta_2=0.999, epsilon=None, schedule_decay=0.004)

model.compile(optimizer= adm1,
              loss='categorical_crossentropy',
              metrics=['accuracy']) 

model.fit(X_train, Y_train, batch_size=128, epochs=400, shuffle=True, verbose=1, validation_split=0.1,callbacks=[tensorboard])

loss = model.evaluate(X_test, Y_test, batch_size=64, verbose=1)

Train on 32000 samples, validate on 3556 samples
Epoch 1/400
32000/32000 [==============================] - 1s 34us/sample - loss: 0.5628 - accuracy: 0.7395 - val_loss: 0.5786 - val_accuracy: 0.7348
Epoch 2/400
32000/32000 [==============================] - 1s 24us/sample - loss: 0.5601 - accuracy: 0.7416 - val_loss: 0.5786 - val_accuracy: 0.7343
Epoch 3/400
32000/32000 [==============================] - 1s 24us/sample - loss: 0.5614 - accuracy: 0.7418 - val_loss: 0.5784 - val_accuracy: 0.7351
Epoch 4/400
32000/32000 [==============================] - 1s 24us/sample - loss: 0.5618 - accuracy: 0.7402 - val_loss: 0.5783 - val_accuracy: 0.7354
Epoch 5/400
32000/32000 [==============================] - 1s 23us/sample - loss: 0.5602 - accuracy: 0.7425 - val_loss: 0.5781 - val_accuracy: 0.7373
Epoch 6/400
32000/32000 [==============================] - 1s 23us/sample - loss: 0.5632 - accuracy: 0.7408 - val_loss: 0.5779 - val_accuracy: 0.7368
Epoch 7/400
32000/32000 [==========================

Epoch 55/400
32000/32000 [==============================] - 1s 23us/sample - loss: 0.5590 - accuracy: 0.7407 - val_loss: 0.5774 - val_accuracy: 0.7357
Epoch 56/400
32000/32000 [==============================] - 1s 24us/sample - loss: 0.5592 - accuracy: 0.7426 - val_loss: 0.5773 - val_accuracy: 0.7357
Epoch 57/400
32000/32000 [==============================] - 1s 24us/sample - loss: 0.5614 - accuracy: 0.7409 - val_loss: 0.5772 - val_accuracy: 0.7354
Epoch 58/400
32000/32000 [==============================] - 1s 23us/sample - loss: 0.5566 - accuracy: 0.7456 - val_loss: 0.5773 - val_accuracy: 0.7354
Epoch 59/400
32000/32000 [==============================] - 1s 23us/sample - loss: 0.5616 - accuracy: 0.7427 - val_loss: 0.5774 - val_accuracy: 0.7357
Epoch 60/400
32000/32000 [==============================] - 1s 24us/sample - loss: 0.5600 - accuracy: 0.7428 - val_loss: 0.5772 - val_accuracy: 0.7362
Epoch 61/400
32000/32000 [==============================] - 1s 24us/sample - loss: 0.5586 - ac

Epoch 163/400
32000/32000 [==============================] - 1s 27us/sample - loss: 0.5557 - accuracy: 0.7455 - val_loss: 0.5759 - val_accuracy: 0.7368
Epoch 164/400
32000/32000 [==============================] - 1s 27us/sample - loss: 0.5617 - accuracy: 0.7422 - val_loss: 0.5763 - val_accuracy: 0.7373
Epoch 165/400
32000/32000 [==============================] - 1s 25us/sample - loss: 0.5559 - accuracy: 0.7452 - val_loss: 0.5762 - val_accuracy: 0.7371
Epoch 166/400
32000/32000 [==============================] - 1s 24us/sample - loss: 0.5588 - accuracy: 0.7421 - val_loss: 0.5762 - val_accuracy: 0.7365
Epoch 167/400
32000/32000 [==============================] - 1s 24us/sample - loss: 0.5585 - accuracy: 0.7447 - val_loss: 0.5762 - val_accuracy: 0.7368
Epoch 168/400
32000/32000 [==============================] - 1s 24us/sample - loss: 0.5572 - accuracy: 0.7444 - val_loss: 0.5762 - val_accuracy: 0.7365
Epoch 169/400
32000/32000 [==============================] - 1s 24us/sample - loss: 0.55

Epoch 217/400
32000/32000 [==============================] - 1s 24us/sample - loss: 0.5567 - accuracy: 0.7460 - val_loss: 0.5753 - val_accuracy: 0.7354
Epoch 218/400
32000/32000 [==============================] - 1s 24us/sample - loss: 0.5560 - accuracy: 0.7433 - val_loss: 0.5753 - val_accuracy: 0.7351
Epoch 219/400
32000/32000 [==============================] - 1s 23us/sample - loss: 0.5576 - accuracy: 0.7425 - val_loss: 0.5755 - val_accuracy: 0.7345
Epoch 220/400
32000/32000 [==============================] - 1s 24us/sample - loss: 0.5578 - accuracy: 0.7437 - val_loss: 0.5753 - val_accuracy: 0.7354
Epoch 221/400
32000/32000 [==============================] - 1s 24us/sample - loss: 0.5559 - accuracy: 0.7439 - val_loss: 0.5754 - val_accuracy: 0.7345
Epoch 222/400
32000/32000 [==============================] - 1s 23us/sample - loss: 0.5561 - accuracy: 0.7445 - val_loss: 0.5753 - val_accuracy: 0.7351
Epoch 223/400
32000/32000 [==============================] - 1s 24us/sample - loss: 0.55

Epoch 271/400
32000/32000 [==============================] - 1s 24us/sample - loss: 0.5586 - accuracy: 0.7445 - val_loss: 0.5750 - val_accuracy: 0.7371
Epoch 272/400
32000/32000 [==============================] - 1s 24us/sample - loss: 0.5568 - accuracy: 0.7423 - val_loss: 0.5750 - val_accuracy: 0.7368
Epoch 273/400
32000/32000 [==============================] - 1s 24us/sample - loss: 0.5573 - accuracy: 0.7436 - val_loss: 0.5748 - val_accuracy: 0.7359
Epoch 274/400
32000/32000 [==============================] - 1s 24us/sample - loss: 0.5561 - accuracy: 0.7451 - val_loss: 0.5749 - val_accuracy: 0.7368
Epoch 275/400
32000/32000 [==============================] - 1s 23us/sample - loss: 0.5542 - accuracy: 0.7433 - val_loss: 0.5747 - val_accuracy: 0.7362
Epoch 276/400
32000/32000 [==============================] - 1s 24us/sample - loss: 0.5530 - accuracy: 0.7461 - val_loss: 0.5745 - val_accuracy: 0.7357
Epoch 277/400
32000/32000 [==============================] - 1s 24us/sample - loss: 0.55

Epoch 325/400
32000/32000 [==============================] - 1s 23us/sample - loss: 0.5551 - accuracy: 0.7448 - val_loss: 0.5747 - val_accuracy: 0.7359
Epoch 326/400
32000/32000 [==============================] - 1s 23us/sample - loss: 0.5550 - accuracy: 0.7461 - val_loss: 0.5746 - val_accuracy: 0.7365
Epoch 327/400
32000/32000 [==============================] - 1s 23us/sample - loss: 0.5532 - accuracy: 0.7463 - val_loss: 0.5747 - val_accuracy: 0.7362
Epoch 328/400
32000/32000 [==============================] - 1s 24us/sample - loss: 0.5565 - accuracy: 0.7448 - val_loss: 0.5747 - val_accuracy: 0.7354
Epoch 329/400
32000/32000 [==============================] - 1s 23us/sample - loss: 0.5533 - accuracy: 0.7461 - val_loss: 0.5745 - val_accuracy: 0.7365
Epoch 330/400
32000/32000 [==============================] - 1s 23us/sample - loss: 0.5557 - accuracy: 0.7452 - val_loss: 0.5746 - val_accuracy: 0.7362
Epoch 331/400
32000/32000 [==============================] - 1s 23us/sample - loss: 0.55

Epoch 379/400
32000/32000 [==============================] - 1s 24us/sample - loss: 0.5517 - accuracy: 0.7473 - val_loss: 0.5742 - val_accuracy: 0.7371
Epoch 380/400
32000/32000 [==============================] - 1s 24us/sample - loss: 0.5562 - accuracy: 0.7469 - val_loss: 0.5741 - val_accuracy: 0.7365
Epoch 381/400
32000/32000 [==============================] - 1s 24us/sample - loss: 0.5550 - accuracy: 0.7452 - val_loss: 0.5742 - val_accuracy: 0.7368
Epoch 382/400
32000/32000 [==============================] - 1s 24us/sample - loss: 0.5522 - accuracy: 0.7474 - val_loss: 0.5741 - val_accuracy: 0.7371
Epoch 383/400
32000/32000 [==============================] - 1s 24us/sample - loss: 0.5537 - accuracy: 0.7439 - val_loss: 0.5742 - val_accuracy: 0.7373
Epoch 384/400
32000/32000 [==============================] - 1s 24us/sample - loss: 0.5537 - accuracy: 0.7462 - val_loss: 0.5743 - val_accuracy: 0.7371
Epoch 385/400
32000/32000 [==============================] - 1s 24us/sample - loss: 0.55

In [10]:
model.save(os.getcwd() + '/NN_models/5layers_residual2.h5')

In [11]:
model = keras.models.load_model(os.getcwd() + '/NN_models/5layers_residual2.h5')
from sklearn.metrics import confusion_matrix



In [23]:
y_pred = model.predict(X_test)
y_pred = tf.one_hot(tf.argmax(y_pred, axis=1), depth = 3)
#confusion_matrix(Y_test, y_pred, labels=["0-10", "10-30", "30+"])

y_test = Y_test.values

In [24]:
print(y_test[0:10])

[[0 0 1]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [0 0 1]
 [1 0 0]]


In [27]:
confusion_matrix(
    y_pred.numpy().argmax(axis=1), y_pred.numpy().argmax(axis=1))

array([[1912,    0,    0],
       [   0, 1145,    0],
       [   0,    0,  893]])

In [29]:
confusion_matrix(
    y_test.argmax(axis=1), y_pred.numpy().argmax(axis=1))

array([[1707,  225,   70],
       [ 134,  641,  286],
       [  71,  279,  537]])

In [32]:
from sklearn.metrics import precision_recall_fscore_support


precision_recall_fscore_support(y_test, y_pred, average= None)

(array([0.89278243, 0.55982533, 0.60134378]),
 array([0.85392696, 0.60414703, 0.6054115 ]),
 array([0.87292253, 0.58114234, 0.60337079]),
 array([1999, 1061,  887]))