In [1]:
import tensorflow as tf
from tensorflow import keras

from time import time
from tensorflow.python.keras.callbacks import TensorBoard

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler

print(tf.__version__)

2.0.0-beta0


In [2]:
PATH = os.getcwd()

df = pd.read_csv(PATH + "/data/k.csv", header=0)
data = df.values

In [3]:
num_samples = df.shape[0]
num_features = df.shape[1]
print("number of samples = " + str(num_samples))
print("number of features = " + str(num_features))
print(df.columns)

number of samples = 39508
number of features = 77
Index(['localx_X', 'localy_X', 'vel_X', 'acc_X', 'laneID_X', 'localx_Y',
       'localy_Y', 'vel_Y', 'acc_Y', 'laneID_Y', 'relative_x', 'relative_y',
       'relative_distance', 'num_lanes', 'duration', 'direction_X__1.0',
       'direction_X__2.0', 'direction_X__3.0', 'direction_X__4.0',
       'direction_Y__1.0', 'direction_Y__2.0', 'direction_Y__3.0',
       'direction_Y__4.0', 'movement_X__1.0', 'movement_X__2.0',
       'movement_X__3.0', 'movement_Y__1.0', 'movement_Y__2.0',
       'movement_Y__3.0', 'exit_X__201.0', 'exit_X__203.0', 'exit_X__204.0',
       'exit_X__205.0', 'exit_X__206.0', 'exit_X__207.0', 'exit_X__208.0',
       'exit_X__209.0', 'exit_X__210.0', 'exit_X__211.0', 'exit_Y__201.0',
       'exit_Y__203.0', 'exit_Y__204.0', 'exit_Y__205.0', 'exit_Y__206.0',
       'exit_Y__207.0', 'exit_Y__208.0', 'exit_Y__209.0', 'exit_Y__210.0',
       'exit_Y__211.0', 'int_X__0.0', 'int_X__1.0', 'int_X__2.0', 'int_X__3.0',
       

In [4]:
X = df.drop(['zero_to_10', 'ten_to_30', 'thirty_plus','duration'], axis=1)
#Y = df[['zero_to_10', 'ten_to_30', 'thirty_plus']]
Y = df[['zero_to_10', 'ten_to_30', 'thirty_plus']]

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.10)

In [5]:
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)

#Y_train = Y_train / 1000
print(X_train[0][:] )
#print(Y_train[0])

scaler = StandardScaler()
scaler.fit(X_test)
X_test = scaler.transform(X_test)

#Y_test = Y_test / 1000
print(X_test[0][:] )
#print(Y_test[0])

[ 1.19306857  1.43221395  1.49122754  2.0739992   0.07428243 -0.71435337
  1.13903064  0.54066897  0.78292709 -0.58824295 -2.08191479 -1.14330605
  1.18964384  0.         -0.16993572  1.1407997  -0.1715929  -1.01779191
 -0.17063522 -0.87838543 -0.16967275  0.98373603  0.29287579 -0.23098372
 -0.1708097   0.29123113 -0.22922211 -0.17054792 -0.63414919 -0.57720955
 -0.14253498 -0.13720501 -0.06659601 -0.20162359  1.42305932 -0.06219221
 -0.09544633 -0.19865952 -0.63506479  1.73729507 -0.14140107 -0.13635148
 -0.06765292 -0.20094286 -0.70387269 -0.06264629 -0.09559624 -0.19942309
  0.51343927 -0.17783265 -0.34668107 -0.17185326 -0.20935439 -1.94648955
 -0.17959227 -0.34632468  5.810127   -0.20862148 -0.55559522 -0.03638091
 -0.63471597 -0.73013141  2.85771548 -0.13847616  1.80268448 -0.03789956
 -0.63358249 -0.73144461 -0.35063827 -0.13837065 -0.56257224  0.13110817
  0.        ]
[-0.62219907  0.01838096  0.23898431 -2.19132712  1.8104302  -1.54805107
  0.04340524  1.90556947  2.44610783 

In [8]:
tensorboard = TensorBoard(log_dir = "logs/{}".format(time()))

In [9]:
model = keras.Sequential(
)

model.add(keras.layers.Dense(256,input_shape=(73,)))

model.add(keras.layers.BatchNormalization())
model.add(keras.layers.Activation('relu'))
model.add(keras.layers.Dropout(0.5))

model.add(keras.layers.Dense(256))
model.add(keras.layers.Activation('relu'))
model.add(keras.layers.Dropout(0.5))

model.add(keras.layers.Dense(3, activation='softmax'))

adm = keras.optimizers.Adam(lr=0.00005, beta_1=0.9, beta_2=0.999, epsilon=None,  amsgrad=False)
#Nadam = keras.optimizers.Nadam(lr=0.002, beta_1=0.9, beta_2=0.999, epsilon=None, schedule_decay=0.004)

model.compile(optimizer= adm,
              loss='categorical_crossentropy',
              metrics=['accuracy']) 

#model.fit(X_train, Y_train, batch_size=64, epochs=1000, shuffle=True, verbose=1, validation_split=0.1)
model.fit(X_train, Y_train, batch_size=64, epochs=400, shuffle=True, verbose=1, validation_split=0.1,callbacks=[tensorboard])
print('\ntest set:')
loss = model.evaluate(X_test, Y_test, batch_size=64, verbose=1)
#print(" accuracy: %f" % (loss[0]))

Train on 32001 samples, validate on 3556 samples
Epoch 1/400
32001/32001 [==============================] - 1s 42us/sample - loss: 1.1868 - accuracy: 0.4775 - val_loss: 0.8779 - val_accuracy: 0.6080
Epoch 2/400
32001/32001 [==============================] - 1s 26us/sample - loss: 1.0313 - accuracy: 0.5470 - val_loss: 0.8165 - val_accuracy: 0.6420
Epoch 3/400
32001/32001 [==============================] - 1s 25us/sample - loss: 0.9555 - accuracy: 0.5709 - val_loss: 0.7885 - val_accuracy: 0.6482
Epoch 4/400
32001/32001 [==============================] - 1s 27us/sample - loss: 0.9132 - accuracy: 0.5926 - val_loss: 0.7719 - val_accuracy: 0.6541
Epoch 5/400
32001/32001 [==============================] - 1s 25us/sample - loss: 0.8825 - accuracy: 0.6018 - val_loss: 0.7596 - val_accuracy: 0.6609
Epoch 6/400
32001/32001 [==============================] - 1s 25us/sample - loss: 0.8578 - accuracy: 0.6104 - val_loss: 0.7512 - val_accuracy: 0.6656
Epoch 7/400
32001/32001 [==========================

Epoch 55/400
32001/32001 [==============================] - 1s 24us/sample - loss: 0.6487 - accuracy: 0.6967 - val_loss: 0.6163 - val_accuracy: 0.7250
Epoch 56/400
32001/32001 [==============================] - 1s 24us/sample - loss: 0.6447 - accuracy: 0.7007 - val_loss: 0.6162 - val_accuracy: 0.7236
Epoch 57/400
32001/32001 [==============================] - 1s 24us/sample - loss: 0.6467 - accuracy: 0.6974 - val_loss: 0.6152 - val_accuracy: 0.7247
Epoch 58/400
32001/32001 [==============================] - 1s 24us/sample - loss: 0.6423 - accuracy: 0.7008 - val_loss: 0.6148 - val_accuracy: 0.7264
Epoch 59/400
32001/32001 [==============================] - 1s 23us/sample - loss: 0.6411 - accuracy: 0.7024 - val_loss: 0.6138 - val_accuracy: 0.7267
Epoch 60/400
32001/32001 [==============================] - 1s 24us/sample - loss: 0.6401 - accuracy: 0.7016 - val_loss: 0.6115 - val_accuracy: 0.7250
Epoch 61/400
32001/32001 [==============================] - 1s 23us/sample - loss: 0.6418 - ac

32001/32001 [==============================] - 1s 24us/sample - loss: 0.6065 - accuracy: 0.7190 - val_loss: 0.5874 - val_accuracy: 0.7359
Epoch 110/400
32001/32001 [==============================] - 1s 40us/sample - loss: 0.6061 - accuracy: 0.7194 - val_loss: 0.5876 - val_accuracy: 0.7351
Epoch 111/400
32001/32001 [==============================] - 1s 24us/sample - loss: 0.6043 - accuracy: 0.7174 - val_loss: 0.5872 - val_accuracy: 0.7365
Epoch 112/400
32001/32001 [==============================] - 1s 32us/sample - loss: 0.6052 - accuracy: 0.7173 - val_loss: 0.5851 - val_accuracy: 0.7348
Epoch 113/400
32001/32001 [==============================] - 1s 28us/sample - loss: 0.6053 - accuracy: 0.7185 - val_loss: 0.5856 - val_accuracy: 0.7362
Epoch 114/400
32001/32001 [==============================] - 1s 24us/sample - loss: 0.6053 - accuracy: 0.7180 - val_loss: 0.5869 - val_accuracy: 0.7362
Epoch 115/400
32001/32001 [==============================] - 1s 24us/sample - loss: 0.6038 - accuracy:

Epoch 163/400
32001/32001 [==============================] - 1s 30us/sample - loss: 0.5865 - accuracy: 0.7293 - val_loss: 0.5742 - val_accuracy: 0.7404
Epoch 164/400
32001/32001 [==============================] - 1s 29us/sample - loss: 0.5866 - accuracy: 0.7291 - val_loss: 0.5743 - val_accuracy: 0.7390
Epoch 165/400
32001/32001 [==============================] - 1s 31us/sample - loss: 0.5860 - accuracy: 0.7294 - val_loss: 0.5741 - val_accuracy: 0.7404
Epoch 166/400
32001/32001 [==============================] - 1s 27us/sample - loss: 0.5854 - accuracy: 0.7292 - val_loss: 0.5732 - val_accuracy: 0.7396
Epoch 167/400
32001/32001 [==============================] - 1s 24us/sample - loss: 0.5831 - accuracy: 0.7297 - val_loss: 0.5734 - val_accuracy: 0.7390
Epoch 168/400
32001/32001 [==============================] - 1s 24us/sample - loss: 0.5872 - accuracy: 0.7283 - val_loss: 0.5732 - val_accuracy: 0.7410
Epoch 169/400
32001/32001 [==============================] - 1s 24us/sample - loss: 0.58

Epoch 217/400
32001/32001 [==============================] - 1s 24us/sample - loss: 0.5726 - accuracy: 0.7374 - val_loss: 0.5655 - val_accuracy: 0.7427
Epoch 218/400
32001/32001 [==============================] - 1s 24us/sample - loss: 0.5679 - accuracy: 0.7384 - val_loss: 0.5645 - val_accuracy: 0.7421
Epoch 219/400
32001/32001 [==============================] - 1s 24us/sample - loss: 0.5688 - accuracy: 0.7368 - val_loss: 0.5650 - val_accuracy: 0.7421
Epoch 220/400
32001/32001 [==============================] - 1s 24us/sample - loss: 0.5704 - accuracy: 0.7368 - val_loss: 0.5646 - val_accuracy: 0.7413
Epoch 221/400
32001/32001 [==============================] - 1s 24us/sample - loss: 0.5687 - accuracy: 0.7373 - val_loss: 0.5642 - val_accuracy: 0.7444
Epoch 222/400
32001/32001 [==============================] - 1s 24us/sample - loss: 0.5681 - accuracy: 0.7367 - val_loss: 0.5648 - val_accuracy: 0.7407
Epoch 223/400
32001/32001 [==============================] - 1s 24us/sample - loss: 0.57

Epoch 271/400
32001/32001 [==============================] - 1s 24us/sample - loss: 0.5595 - accuracy: 0.7445 - val_loss: 0.5605 - val_accuracy: 0.7472
Epoch 272/400
32001/32001 [==============================] - 1s 24us/sample - loss: 0.5642 - accuracy: 0.7439 - val_loss: 0.5612 - val_accuracy: 0.7469
Epoch 273/400
32001/32001 [==============================] - 1s 24us/sample - loss: 0.5590 - accuracy: 0.7409 - val_loss: 0.5595 - val_accuracy: 0.7492
Epoch 274/400
32001/32001 [==============================] - 1s 24us/sample - loss: 0.5605 - accuracy: 0.7438 - val_loss: 0.5596 - val_accuracy: 0.7466
Epoch 275/400
32001/32001 [==============================] - 1s 24us/sample - loss: 0.5622 - accuracy: 0.7424 - val_loss: 0.5588 - val_accuracy: 0.7489
Epoch 276/400
32001/32001 [==============================] - 1s 23us/sample - loss: 0.5579 - accuracy: 0.7422 - val_loss: 0.5583 - val_accuracy: 0.7483
Epoch 277/400
32001/32001 [==============================] - 1s 24us/sample - loss: 0.56

Epoch 325/400
32001/32001 [==============================] - 1s 24us/sample - loss: 0.5514 - accuracy: 0.7463 - val_loss: 0.5551 - val_accuracy: 0.7492
Epoch 326/400
32001/32001 [==============================] - 1s 24us/sample - loss: 0.5512 - accuracy: 0.7456 - val_loss: 0.5554 - val_accuracy: 0.7489
Epoch 327/400
32001/32001 [==============================] - 1s 24us/sample - loss: 0.5491 - accuracy: 0.7485 - val_loss: 0.5554 - val_accuracy: 0.7478
Epoch 328/400
32001/32001 [==============================] - 1s 24us/sample - loss: 0.5500 - accuracy: 0.7503 - val_loss: 0.5543 - val_accuracy: 0.7497
Epoch 329/400
32001/32001 [==============================] - 1s 24us/sample - loss: 0.5497 - accuracy: 0.7489 - val_loss: 0.5541 - val_accuracy: 0.7492
Epoch 330/400
32001/32001 [==============================] - 1s 24us/sample - loss: 0.5455 - accuracy: 0.7472 - val_loss: 0.5543 - val_accuracy: 0.7480
Epoch 331/400
32001/32001 [==============================] - 1s 24us/sample - loss: 0.55

Epoch 379/400
32001/32001 [==============================] - 1s 35us/sample - loss: 0.5434 - accuracy: 0.7506 - val_loss: 0.5508 - val_accuracy: 0.7489
Epoch 380/400
32001/32001 [==============================] - 1s 29us/sample - loss: 0.5417 - accuracy: 0.7525 - val_loss: 0.5511 - val_accuracy: 0.7503
Epoch 381/400
32001/32001 [==============================] - 1s 29us/sample - loss: 0.5447 - accuracy: 0.7515 - val_loss: 0.5510 - val_accuracy: 0.7520
Epoch 382/400
32001/32001 [==============================] - 1s 28us/sample - loss: 0.5406 - accuracy: 0.7545 - val_loss: 0.5498 - val_accuracy: 0.7520
Epoch 383/400
32001/32001 [==============================] - 1s 30us/sample - loss: 0.5395 - accuracy: 0.7529 - val_loss: 0.5510 - val_accuracy: 0.7492
Epoch 384/400
32001/32001 [==============================] - 1s 31us/sample - loss: 0.5410 - accuracy: 0.7514 - val_loss: 0.5515 - val_accuracy: 0.7492
Epoch 385/400
32001/32001 [==============================] - 1s 30us/sample - loss: 0.53

In [125]:
model.save(PATH + '/NN_models/3layers_mlp.h5')

# Recreate the exact same model purely from the file
model = keras.models.load_model(PATH + '/NN_models/3layers_mlp.h5')

In [126]:
adm1 = keras.optimizers.Adam(lr=0.00001, beta_1=0.9, beta_2=0.999, epsilon=None,  amsgrad=False)
#Nadam = keras.optimizers.Nadam(lr=0.002, beta_1=0.9, beta_2=0.999, epsilon=None, schedule_decay=0.004)

model.compile(optimizer= adm1,
              loss='categorical_crossentropy',
              metrics=['accuracy']) 

#model.fit(X_train, Y_train, batch_size=64, epochs=1000, shuffle=True, verbose=1, validation_split=0.1)
model.fit(X_train, Y_train, batch_size=128, epochs=500, shuffle=True, verbose=1, validation_split=0.1,callbacks=[tensorboard])

loss = model.evaluate(X_test, Y_test, batch_size=64, verbose=1)

Train on 32001 samples, validate on 3556 samples
Epoch 1/500
32001/32001 [==============================] - 1s 38us/sample - loss: 0.5310 - accuracy: 0.7573 - val_loss: 0.5504 - val_accuracy: 0.7514
Epoch 2/500
32001/32001 [==============================] - 1s 19us/sample - loss: 0.5305 - accuracy: 0.7558 - val_loss: 0.5503 - val_accuracy: 0.7520
Epoch 3/500
32001/32001 [==============================] - 1s 18us/sample - loss: 0.5275 - accuracy: 0.7584 - val_loss: 0.5497 - val_accuracy: 0.7548
Epoch 4/500
32001/32001 [==============================] - 1s 19us/sample - loss: 0.5282 - accuracy: 0.7577 - val_loss: 0.5492 - val_accuracy: 0.7528
Epoch 5/500
32001/32001 [==============================] - 1s 18us/sample - loss: 0.5297 - accuracy: 0.7559 - val_loss: 0.5493 - val_accuracy: 0.7542
Epoch 6/500
32001/32001 [==============================] - 1s 18us/sample - loss: 0.5329 - accuracy: 0.7582 - val_loss: 0.5493 - val_accuracy: 0.7528
Epoch 7/500
32001/32001 [==========================

Epoch 55/500
32001/32001 [==============================] - 1s 19us/sample - loss: 0.5272 - accuracy: 0.7608 - val_loss: 0.5499 - val_accuracy: 0.7520
Epoch 56/500
32001/32001 [==============================] - 1s 18us/sample - loss: 0.5307 - accuracy: 0.7569 - val_loss: 0.5492 - val_accuracy: 0.7534
Epoch 57/500
32001/32001 [==============================] - 1s 19us/sample - loss: 0.5277 - accuracy: 0.7588 - val_loss: 0.5495 - val_accuracy: 0.7534
Epoch 58/500
32001/32001 [==============================] - 1s 18us/sample - loss: 0.5300 - accuracy: 0.7571 - val_loss: 0.5498 - val_accuracy: 0.7539
Epoch 59/500
32001/32001 [==============================] - 1s 19us/sample - loss: 0.5274 - accuracy: 0.7574 - val_loss: 0.5500 - val_accuracy: 0.7537
Epoch 60/500
32001/32001 [==============================] - 1s 18us/sample - loss: 0.5289 - accuracy: 0.7585 - val_loss: 0.5506 - val_accuracy: 0.7520
Epoch 61/500
32001/32001 [==============================] - 1s 18us/sample - loss: 0.5253 - ac

32001/32001 [==============================] - 1s 19us/sample - loss: 0.5266 - accuracy: 0.7591 - val_loss: 0.5491 - val_accuracy: 0.7520
Epoch 110/500
32001/32001 [==============================] - 1s 20us/sample - loss: 0.5264 - accuracy: 0.7605 - val_loss: 0.5489 - val_accuracy: 0.7534
Epoch 111/500
32001/32001 [==============================] - 1s 17us/sample - loss: 0.5257 - accuracy: 0.7619 - val_loss: 0.5489 - val_accuracy: 0.7525
Epoch 112/500
32001/32001 [==============================] - 1s 19us/sample - loss: 0.5276 - accuracy: 0.7580 - val_loss: 0.5489 - val_accuracy: 0.7522
Epoch 113/500
32001/32001 [==============================] - 1s 19us/sample - loss: 0.5259 - accuracy: 0.7614 - val_loss: 0.5490 - val_accuracy: 0.7534
Epoch 114/500
32001/32001 [==============================] - 1s 19us/sample - loss: 0.5280 - accuracy: 0.7587 - val_loss: 0.5484 - val_accuracy: 0.7539
Epoch 115/500
32001/32001 [==============================] - 1s 19us/sample - loss: 0.5254 - accuracy:

Epoch 163/500
32001/32001 [==============================] - 1s 17us/sample - loss: 0.5261 - accuracy: 0.7582 - val_loss: 0.5495 - val_accuracy: 0.7528
Epoch 164/500
32001/32001 [==============================] - 1s 17us/sample - loss: 0.5252 - accuracy: 0.7609 - val_loss: 0.5495 - val_accuracy: 0.7545
Epoch 165/500
32001/32001 [==============================] - 1s 21us/sample - loss: 0.5246 - accuracy: 0.7599 - val_loss: 0.5490 - val_accuracy: 0.7545
Epoch 166/500
32001/32001 [==============================] - 1s 22us/sample - loss: 0.5270 - accuracy: 0.7599 - val_loss: 0.5490 - val_accuracy: 0.7545
Epoch 167/500
32001/32001 [==============================] - 1s 19us/sample - loss: 0.5283 - accuracy: 0.7579 - val_loss: 0.5491 - val_accuracy: 0.7551
Epoch 168/500
32001/32001 [==============================] - 1s 18us/sample - loss: 0.5254 - accuracy: 0.7599 - val_loss: 0.5488 - val_accuracy: 0.7539
Epoch 169/500
32001/32001 [==============================] - 1s 18us/sample - loss: 0.52

Epoch 217/500
32001/32001 [==============================] - 1s 18us/sample - loss: 0.5217 - accuracy: 0.7626 - val_loss: 0.5481 - val_accuracy: 0.7576
Epoch 218/500
32001/32001 [==============================] - 1s 23us/sample - loss: 0.5260 - accuracy: 0.7573 - val_loss: 0.5485 - val_accuracy: 0.7551
Epoch 219/500
32001/32001 [==============================] - 1s 18us/sample - loss: 0.5261 - accuracy: 0.7594 - val_loss: 0.5484 - val_accuracy: 0.7567
Epoch 220/500
32001/32001 [==============================] - 1s 18us/sample - loss: 0.5249 - accuracy: 0.7630 - val_loss: 0.5484 - val_accuracy: 0.7559
Epoch 221/500
32001/32001 [==============================] - 1s 18us/sample - loss: 0.5224 - accuracy: 0.7593 - val_loss: 0.5481 - val_accuracy: 0.7562
Epoch 222/500
32001/32001 [==============================] - 1s 19us/sample - loss: 0.5217 - accuracy: 0.7610 - val_loss: 0.5479 - val_accuracy: 0.7567
Epoch 223/500
32001/32001 [==============================] - 1s 18us/sample - loss: 0.52

Epoch 271/500
32001/32001 [==============================] - 1s 19us/sample - loss: 0.5240 - accuracy: 0.7591 - val_loss: 0.5477 - val_accuracy: 0.7553
Epoch 272/500
32001/32001 [==============================] - 1s 22us/sample - loss: 0.5212 - accuracy: 0.7628 - val_loss: 0.5478 - val_accuracy: 0.7573
Epoch 273/500
32001/32001 [==============================] - 1s 25us/sample - loss: 0.5238 - accuracy: 0.7617 - val_loss: 0.5483 - val_accuracy: 0.7567
Epoch 274/500
32001/32001 [==============================] - 1s 23us/sample - loss: 0.5261 - accuracy: 0.7625 - val_loss: 0.5485 - val_accuracy: 0.7551
Epoch 275/500
32001/32001 [==============================] - 1s 25us/sample - loss: 0.5234 - accuracy: 0.7607 - val_loss: 0.5484 - val_accuracy: 0.7559
Epoch 276/500
32001/32001 [==============================] - 1s 26us/sample - loss: 0.5211 - accuracy: 0.7619 - val_loss: 0.5483 - val_accuracy: 0.7570
Epoch 277/500
32001/32001 [==============================] - 1s 22us/sample - loss: 0.52

Epoch 325/500
32001/32001 [==============================] - 1s 19us/sample - loss: 0.5199 - accuracy: 0.7619 - val_loss: 0.5477 - val_accuracy: 0.7562
Epoch 326/500
32001/32001 [==============================] - 1s 17us/sample - loss: 0.5212 - accuracy: 0.7618 - val_loss: 0.5478 - val_accuracy: 0.7562
Epoch 327/500
32001/32001 [==============================] - 1s 17us/sample - loss: 0.5215 - accuracy: 0.7595 - val_loss: 0.5482 - val_accuracy: 0.7556
Epoch 328/500
32001/32001 [==============================] - 1s 19us/sample - loss: 0.5184 - accuracy: 0.7647 - val_loss: 0.5475 - val_accuracy: 0.7565
Epoch 329/500
32001/32001 [==============================] - 1s 17us/sample - loss: 0.5238 - accuracy: 0.7607 - val_loss: 0.5474 - val_accuracy: 0.7556
Epoch 330/500
32001/32001 [==============================] - 1s 19us/sample - loss: 0.5201 - accuracy: 0.7606 - val_loss: 0.5477 - val_accuracy: 0.7562
Epoch 331/500
32001/32001 [==============================] - 1s 17us/sample - loss: 0.52

Epoch 379/500
32001/32001 [==============================] - 1s 17us/sample - loss: 0.5223 - accuracy: 0.7621 - val_loss: 0.5479 - val_accuracy: 0.7570
Epoch 380/500
32001/32001 [==============================] - 1s 16us/sample - loss: 0.5185 - accuracy: 0.7652 - val_loss: 0.5474 - val_accuracy: 0.7576
Epoch 381/500
32001/32001 [==============================] - 1s 17us/sample - loss: 0.5200 - accuracy: 0.7659 - val_loss: 0.5472 - val_accuracy: 0.7582
Epoch 382/500
32001/32001 [==============================] - 1s 17us/sample - loss: 0.5182 - accuracy: 0.7639 - val_loss: 0.5471 - val_accuracy: 0.7567
Epoch 383/500
32001/32001 [==============================] - 1s 16us/sample - loss: 0.5223 - accuracy: 0.7632 - val_loss: 0.5471 - val_accuracy: 0.7579
Epoch 384/500
32001/32001 [==============================] - 1s 16us/sample - loss: 0.5209 - accuracy: 0.7646 - val_loss: 0.5476 - val_accuracy: 0.7562
Epoch 385/500
32001/32001 [==============================] - 1s 18us/sample - loss: 0.51

Epoch 433/500
32001/32001 [==============================] - 1s 19us/sample - loss: 0.5203 - accuracy: 0.7594 - val_loss: 0.5468 - val_accuracy: 0.7553
Epoch 434/500
32001/32001 [==============================] - 1s 23us/sample - loss: 0.5203 - accuracy: 0.7634 - val_loss: 0.5470 - val_accuracy: 0.7565
Epoch 435/500
32001/32001 [==============================] - 1s 16us/sample - loss: 0.5192 - accuracy: 0.7639 - val_loss: 0.5468 - val_accuracy: 0.7582
Epoch 436/500
32001/32001 [==============================] - 1s 17us/sample - loss: 0.5188 - accuracy: 0.7635 - val_loss: 0.5465 - val_accuracy: 0.7565
Epoch 437/500
32001/32001 [==============================] - 1s 20us/sample - loss: 0.5196 - accuracy: 0.7636 - val_loss: 0.5469 - val_accuracy: 0.7559
Epoch 438/500
32001/32001 [==============================] - 1s 18us/sample - loss: 0.5177 - accuracy: 0.7618 - val_loss: 0.5474 - val_accuracy: 0.7562
Epoch 439/500
32001/32001 [==============================] - 1s 16us/sample - loss: 0.52

Epoch 487/500
32001/32001 [==============================] - 1s 16us/sample - loss: 0.5194 - accuracy: 0.7633 - val_loss: 0.5469 - val_accuracy: 0.7573
Epoch 488/500
32001/32001 [==============================] - 1s 17us/sample - loss: 0.5213 - accuracy: 0.7632 - val_loss: 0.5469 - val_accuracy: 0.7565
Epoch 489/500
32001/32001 [==============================] - 1s 17us/sample - loss: 0.5193 - accuracy: 0.7628 - val_loss: 0.5471 - val_accuracy: 0.7565
Epoch 490/500
32001/32001 [==============================] - 1s 17us/sample - loss: 0.5158 - accuracy: 0.7648 - val_loss: 0.5468 - val_accuracy: 0.7584
Epoch 491/500
32001/32001 [==============================] - 1s 17us/sample - loss: 0.5178 - accuracy: 0.7631 - val_loss: 0.5467 - val_accuracy: 0.7562
Epoch 492/500
32001/32001 [==============================] - 1s 18us/sample - loss: 0.5199 - accuracy: 0.7626 - val_loss: 0.5469 - val_accuracy: 0.7562
Epoch 493/500
32001/32001 [==============================] - 1s 19us/sample - loss: 0.51

In [132]:
model.save(PATH + '/NN_models/3layers_mlp.h5')
#p1 = np.savetxt("ytest.csv", Y_test, delimiter=",",fmt = "%s")
#p = np.savetxt("pred.csv", preds, delimiter=",",fmt = "%s")

In [22]:
clf.fit(X_train,Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [23]:
import pickle
from sklearn import metrics

with open(PATH + '/Random_Forest/rf3.cpickle', 'wb') as f:
    pickle.dump(clf, f)

# in your prediction file                                                                                                                                                                                                           

with open(PATH + '/Random_Forest/rf3.cpickle', 'rb') as f:
    clf = pickle.load(f)


preds = clf.predict(X_test)
print("Accuracy:",metrics.accuracy_score(Y_test, preds))

Accuracy: 0.6522399392558846


In [54]:
print(preds)

[[1 0 0]
 [0 1 0]
 [0 1 0]
 ...
 [1 0 0]
 [1 0 0]
 [1 0 0]]


In [26]:
k = df.drop(['zero_to_10', 'ten_to_30', 'thirty_plus','duration'], axis=1)

feature_imp = pd.Series(clf.feature_importances_,index=k.columns).sort_values(ascending=False)
print(feature_imp)

vel_Y                0.088487
vel_X                0.087832
distance_x_toexit    0.072037
distance_y_toexit    0.071521
relative_distance    0.063202
localx_X             0.059435
localx_Y             0.058501
localy_Y             0.055093
localy_X             0.054610
relative_x           0.051258
relative_y           0.047325
acc_Y                0.039563
acc_X                0.037899
laneID_Y             0.019848
laneID_X             0.018868
direction_Y__4.0     0.013466
direction_X__4.0     0.012878
direction_Y__2.0     0.011392
direction_X__2.0     0.010012
exit_X__201.0        0.008428
exit_Y__208.0        0.008316
exit_Y__201.0        0.007703
exit_X__203.0        0.007495
exit_X__208.0        0.007422
exit_Y__203.0        0.007008
section_Y__0.0       0.005864
section_X__0.0       0.005612
int_X__2.0           0.004200
int_Y__2.0           0.003999
int_Y__0.0           0.003895
                       ...   
movement_Y__2.0      0.001501
movement_X__2.0      0.001422
exit_Y__20

In [128]:
def ensemble_prediction(predictions):
    after = []
    #final_pred = np.zeros(3)
    for i in range(0,len(X_test)):
        if np.array_equal(predictions[0][i],predictions[1][i]):
            mo = predictions[0][i]
            after.append(list(mo))
            continue
        if np.array_equal(predictions[0][i],predictions[2][i]):
            mo = predictions[0][i]
            after.append(list(mo))
            continue
        if np.array_equal(predictions[1][i],predictions[2][i]):
            mo = predictions[1][i]
            after.append(list(mo))
            continue
        after.append(list(mo))
    out = np.asarray(after)
    return out

In [129]:
#ensemble
import statistics
model1 = keras.models.load_model(PATH + '/NN_models/3layers_mlp.h5')
model2 = keras.models.load_model(PATH + '/NN_models/5layers_residual.h5')
model3 = clf

pred1=model1.predict(X_test)
pred1 = tf.one_hot(tf.argmax(pred1, axis=1), depth = 3)
pred2=model2.predict(X_test)
pred2 = tf.one_hot(tf.argmax(pred2, axis=1), depth = 3)
pred3=model3.predict(X_test)
pred3 = tf.one_hot(tf.argmax(pred2, axis=1), depth = 3)

#print(pred2)

predictions = [pred1, pred2, pred3]
print(pred1.shape)

(3951, 3)


In [131]:
ye = ensemble_prediction(predictions)
print(ye.shape)
print("Accuracy:",metrics.accuracy_score(Y_test, ye))


(3951, 3)
Accuracy: 0.794735509997469
