In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

import os
import numpy as np
import pandas as pd
import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

import pickle

In [3]:
PATH = os.getcwd()
print(PATH)

scriptdir = os.path.dirname(os.path.abspath(PATH))
print(scriptdir)
PATH = scriptdir

/Users/JunxiChen/Documents/MOTIVE_LinkDuration/SVM
/Users/JunxiChen/Documents/MOTIVE_LinkDuration


In [4]:
X_train = pd.read_csv(PATH + "/Train/X_train_5int.csv", header=0)
Y_train = pd.read_csv(PATH + "/Train/Y_train_5int.csv", header=0)

X_test = pd.read_csv(PATH + "/Test/X_test_5int.csv", header=0)
Y_test = pd.read_csv(PATH + "/Test/Y_test_5int.csv", header=0)

In [10]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='rbf')
svclassifier.fit(X_train, Y_train)

/Users/JunxiChen/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/JunxiChen/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [11]:
y_pred = svclassifier.predict(X_test)

In [12]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test, y_pred))

[[1172   66    1    0  127]
 [ 213  227    9    1  185]
 [  54   85   10    4  224]
 [  21   52    6    4  192]
 [  59   98   13    2 1125]]
              precision    recall  f1-score   support

         1.0       0.77      0.86      0.81      1366
         2.0       0.43      0.36      0.39       635
         3.0       0.26      0.03      0.05       377
         4.0       0.36      0.01      0.03       275
         5.0       0.61      0.87      0.71      1297

    accuracy                           0.64      3950
   macro avg       0.49      0.42      0.40      3950
weighted avg       0.59      0.64      0.58      3950



In [13]:
y_predt = svclassifier.predict(X_train)
print(confusion_matrix(Y_train, y_predt))
print(classification_report(Y_train, y_predt))

[[11341   458    15     0   937]
 [ 1387  2516    39    14  1640]
 [  309   697   267    26  1938]
 [  186   453    50    77  1735]
 [  333   659    67    20 10390]]
              precision    recall  f1-score   support

         1.0       0.84      0.89      0.86     12751
         2.0       0.53      0.45      0.48      5596
         3.0       0.61      0.08      0.15      3237
         4.0       0.56      0.03      0.06      2501
         5.0       0.62      0.91      0.74     11469

    accuracy                           0.69     35554
   macro avg       0.63      0.47      0.46     35554
weighted avg       0.68      0.69      0.64     35554



In [ ]:

from sklearn import svm

clf = svm.SVC(C=20, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)
#svm.SVC(gamma='scale')
clf.fit(X_train, Y_train)  


In [ ]:
y_pred = clf.predict(X_test)
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test, y_pred))